### ISSUE TITLE
[Bug] avbase change new naming convention 更改命名規則

### ISSUE THREAD

**Issue by Dissyu** [metatube-community/jellyfin-plugin-metatube#214]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki), especially the [FAQ](https://github.com/metatube-community/jellyfin-plugin-metatube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### MetaTube Plugin Version

v2023.503.910.0

### MetaTube Server Version

v1.1.1

### What OS are you seeing the problem on?

Linux

### Description

avbase 似乎更改了新的命名方式，比如說"RCTD-538"這部片，以往插件內容填上: `avbase:rctd-538`，即可搜刮
配合以前的網址會是https://www.avbase.net/works/RCTD-538

但現在網址變成https://www.avbase.net/works/rocket:RCTD-538 ，那手動更改插件內容: `avbase:rocket:rctd-538`
仍然出現404 not found.

Today I found a issue, avbase updated new naming convention, 

Like below this , before Using `avbase:rctd-538`, then video will be succes catch information.

but now update new website address. https://www.avbase.net/works/rocket:RCTD-538

but I change to `avbase:rocker:rctd-538`, still 404 not found error.

**Comment by xjasonlyu** [comment]
Fixed in https://github.com/metatube-community/metatube-sdk-go/releases/tag/v1.1.2

**Comment by Dissyu** [comment]
> Fixed in https://github.com/metatube-community/metatube-sdk-go/releases/tag/v1.1.2

Hello Sir, Still dont work. Is need wait plugin update ?

**Comment by xjasonlyu** [comment]
Have you upgraded your metatube server?

**Comment by Dissyu** [comment]
> Have you upgraded your metatube server?

Yes, I updated my metatube server to v1.1.2

**Comment by xjasonlyu** [comment]
Oh, sorry, just found a bug that caused this issue. Will fix soon.

**Comment by Dissyu** [comment]
> Oh, sorry, just found a bug that caused this issue. Will fix soon.

its ok, I appreciate your effort.
best regards!

**Comment by xjasonlyu** [comment]
Fixed. Try to update both plugin and server.

**Comment by Dissyu** [comment]
> Fixed. Try to update both plugin and server.

Thanks, But I found other issue. below red circle, I click the `metatube` , will open browers to the video .
but now still have some problem, please check about this . thank you
![螢幕擷取畫面 2023-10-14 142603](https://github.com/metatube-community/jellyfin-plugin-metatube/assets/17665081/920ff477-ff15-481a-bdb8-c50ee6e0fcd4)

**Comment by hejunchen** [comment]
thank you for the fix.

**Comment by Dissyu** [comment]
> thank you for the fix.

did you succes enter the website? what above I said.
